baseURL = "https://nonidx.netlify.app"
languageCode = "en-us"
summarylength = 20
[[menu.main]]
name = "Our Team"
parent = "About"
url = "/teams"
weight = 3
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Listings"
url = "/listings"
weight = 2
[[menu.main]]
name = "About"
weight = 4
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 5
[taxonomies]
category = "categories"
city = "city"
property = "property"
state = "state"
status = "status"
tag = "tags"
zip = "zip"
